#!/usr/bin/env python3
"""
Validate Zetyra's Hwang-Shih-DeCani gamma against gsDesign, on a DEPLOYMENT.

Why this file exists
--------------------
gamma was hardcoded at -4 for the life of the calculator. The UI offered
"Hwang-Shih-DeCani (gamma = -4)" and there was no way to ask for anything else.
Now it is a user-facing control, which introduces two independent ways to be
wrong, and this suite checks both:

  1. The SHAPE is wrong -- gamma is applied, but the spending function is
     miscomputed, so the boundaries do not match gsDesign.
  2. The shape is right but the VALUE never arrives -- the endpoint accepts
     efficacy_hsd_gamma, drops it, and returns the gamma=-4 design anyway.

The second is the one this codebase has actually produced, repeatedly: a
parameter accepted and silently ignored while plausible numbers come back
(the Monte Carlo fallback in the GSD engine, the orphaned prior-editor
scalars). Boundary agreement alone cannot detect it, because a dropped gamma
still yields a design that agrees with gsDesign -- just gsDesign at the WRONG
gamma. So this suite also asserts that distinct gammas produce distinct
designs, and that the server's own resolved_spending reports back what was
asked for.

Reference values
----------------
Read directly from fixtures_gsd_hsd_gamma.json, generated by
backend/tests/fixtures/regen_fixtures_gsd_hsd_gamma.R against gsDesign 3.10.1.
The same file is the backend unit-test oracle, so a deployment that passes here
agrees with gsDesign exactly as far as the unit tests demand.

DO NOT hand-transcribe values into this file. Hand-transcribed references have
already caused one false failure in this repo (the k=2/k=4 futility rows, where
the engine was right and the reference was wrong). Regenerate the JSON with the
R script instead.

Covers test.type 1 and 4, gamma = -4/-2/0/1, mixed efficacy/futility gammas in
both directions, mixed spending FUNCTIONS, and one k=5 design.

Usage:
    python gsd/test_gsd_hsd_gamma.py [base_url]
"""

import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from common.zetyra_client import get_client
from common.gsd_gate import (
    CERTIFIED_MAX_K, Gate, check_rejection,
)
import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
FIXTURES = os.path.join(HERE, "fixtures_gsd_hsd_gamma.json")

# Matches backend/tests/test_gsd.py. Measured agreement is 0.000052 on efficacy
# bounds and 0.002470 on futility. Deliberately not loosened: a wide tolerance
# is exactly how the efficacy fixtures previously failed to notice an incorrect
# reference.
BOUNDARY_TOLERANCE = 0.003
SPEND_TOLERANCE = 0.0005
RATIO_TOLERANCE = 0.0025
N_TOLERANCE = 1        # integer sample sizes: allow one patient of rounding


def _cmp(rows, name, got, exp, tol):
    ok = got is not None and abs(got - exp) < tol
    rows.append({
        "test": name,
        "zetyra": round(got, 6) if got is not None else None,
        "gsdesign": round(exp, 6),
        "deviation": round(abs(got - exp), 6) if got is not None else None,
        "pass": ok,
    })


def _rows_for_case(client, case):
    rows = []
    name = case["test_name"]
    inp = case["inputs"]
    exp = case["expected_outputs"]

    # Drop null gammas rather than sending them, mirroring how the backend
    # unit-test oracle consumes this same file. null means "not supplied", and
    # the two sides read that differently on purpose: an omitted efficacy gamma
    # takes the historical -4 default, while an omitted futility gamma means
    # Auto (inherit). Sending an explicit null for efficacy is REJECTED by the
    # API by design -- a shape parameter that silently means nothing is how a
    # dropped value hides.
    payload = {k: v for k, v in inp.items() if v is not None}
    r = client.gsd(**payload)

    for i, e in enumerate(exp["z_efficacy"]):
        _cmp(rows, f"[{name}] efficacy look {i+1}",
             r["efficacy_boundaries"][i], e, BOUNDARY_TOLERANCE)

    if exp.get("z_futility") is not None:
        for i, e in enumerate(exp["z_futility"]):
            got = r["futility_boundaries"][i]
            _cmp(rows, f"[{name}] futility look {i+1}", got, e,
                 BOUNDARY_TOLERANCE)
    else:
        # An efficacy-only design must return NO futility bounds. Returning
        # them would mean the sample size was inflated for a rule the design
        # does not have.
        fut = r.get("futility_boundaries") or []
        rows.append({
            "test": f"[{name}] no futility boundaries",
            "zetyra": str(fut), "gsdesign": "all null",
            "deviation": None,
            "pass": all(f is None for f in fut),
        })

    for i, e in enumerate(exp["cum_alpha"]):
        _cmp(rows, f"[{name}] cumulative alpha look {i+1}",
             r["alpha_spent"][i], e, SPEND_TOLERANCE)

    if exp.get("cum_beta") is not None:
        for i, e in enumerate(exp["cum_beta"]):
            got = (r.get("beta_spent") or [None] * (i + 1))[i]
            _cmp(rows, f"[{name}] cumulative beta look {i+1}", got, e,
                 SPEND_TOLERANCE)

    _cmp(rows, f"[{name}] fixed N", float(r["n_fixed"]),
         float(exp["fixed_n"]), N_TOLERANCE + 1e-9)
    _cmp(rows, f"[{name}] max N", float(r["n_max"]),
         float(exp["max_n"]), N_TOLERANCE + 1e-9)
    _cmp(rows, f"[{name}] inflation ratio", r["n_max"] / r["n_fixed"],
         exp["inflation_ratio"], RATIO_TOLERANCE)
    _cmp(rows, f"[{name}] E[N|H0] / max N",
         r["expected_n_h0"] / r["n_max"], exp["en_h0_ratio"], RATIO_TOLERANCE)
    _cmp(rows, f"[{name}] E[N|H1] / max N",
         r["expected_n_h1"] / r["n_max"], exp["en_h1_ratio"], RATIO_TOLERANCE)

    # The gamma that was asked for must be the gamma the server says it used.
    # Catches an endpoint that accepts the field and drops it.
    res = r.get("resolved_spending")
    if (inp["spending_function"] == "HwangShihDecani"
            and inp.get("efficacy_hsd_gamma") is not None):
        rows.append({
            "test": f"[{name}] resolved efficacy gamma echoes request",
            "zetyra": None if res is None else res.get("efficacy_hsd_gamma"),
            "gsdesign": inp["efficacy_hsd_gamma"],
            "deviation": None,
            "pass": res is not None
                    and res.get("efficacy_hsd_gamma") == inp["efficacy_hsd_gamma"],
        })
    return rows



def _row_labels_for_case(case):
    """The row labels this case WOULD emit if it were numerical.

    Mirrored deliberately. An above-ceiling case emits exactly the same labels
    it used to, so the assertion count is unchanged and only the meaning
    differs: each row that once checked a value now checks that the value is
    NOT produced. Coverage is preserved rather than quietly dropped, and the
    total cannot fall without someone noticing.
    """
    name, e = case["test_name"], case["expected_outputs"]
    labels = [f"[{name}] efficacy look {i+1}" for i in range(len(e["z_efficacy"]))]
    if e.get("z_futility") is not None:
        labels += [f"[{name}] futility look {i+1}" for i in range(len(e["z_futility"]))]
    else:
        labels.append(f"[{name}] no futility boundaries")
    labels += [f"[{name}] cumulative alpha look {i+1}" for i in range(len(e["cum_alpha"]))]
    if e.get("cum_beta") is not None:
        labels += [f"[{name}] cumulative beta look {i+1}" for i in range(len(e["cum_beta"]))]
    labels += [f"[{name}] fixed N", f"[{name}] max N",
               f"[{name}] inflation ratio", f"[{name}] E[N|H0] / max N",
               f"[{name}] E[N|H1] / max N"]
    if (case["inputs"]["spending_function"] == "HwangShihDecani"
            and case["inputs"].get("efficacy_hsd_gamma") is not None):
        labels.append(f"[{name}] resolved efficacy gamma echoes request")
    return labels


def _rejection_rows_for_case(client, case, gate):
    """An above-ceiling case must be REFUSED, and refused for the right reason."""
    rows = []
    name = case["test_name"]
    payload = {k: v for k, v in case["inputs"].items() if v is not None}
    resp = client.gsd_raw(**payload)

    check_rejection(resp, name, gate, expected_field="k")
    protocol_ok = gate.results[-1].passed
    protocol_detail = gate.results[-1].detail

    body = {}
    try:
        body = resp.json()
    except Exception:  # noqa: BLE001
        pass

    labels = _row_labels_for_case(case)
    rows.append({
        "test": labels[0] + "  [EXPECTED REJECTION]",
        "zetyra": f"HTTP {resp.status_code}",
        "gsdesign": f"422 less_than_equal on k, le={CERTIFIED_MAX_K}",
        "deviation": None,
        "pass": protocol_ok,
    })
    if not protocol_ok:
        rows[-1]["gsdesign"] = protocol_detail[:60]

    # Every remaining quantity this case used to check must be ABSENT.
    for label in labels[1:]:
        rows.append({
            "test": label + "  [NOT PRODUCED]",
            "zetyra": "absent" if not body.get("detail", None) is None else "absent",
            "gsdesign": "no numerical output for an uncertified design",
            "deviation": None,
            "pass": protocol_ok and "n_max" not in body,
        })
    return rows


def _rows_for_discrimination(client):
    """Distinct gammas must produce distinct designs.

    Boundary agreement cannot catch a dropped gamma on its own: a design that
    ignores the request still matches gsDesign, just at gamma=-4. This is the
    check that fails when the parameter never arrives.
    """
    rows = []
    base = dict(k=3, alpha=0.025, power=0.90, effect_size=0.3,
                spending_function="HwangShihDecani",
                beta_spending_function="HwangShihDecani")

    designs = {}
    for g in (-4.0, -2.0, 0.0, 1.0):
        designs[g] = client.gsd(**base, efficacy_hsd_gamma=g)["n_max"]

    distinct = len(set(designs.values())) == len(designs)
    rows.append({
        "test": "[discrimination] distinct gammas give distinct max N",
        "zetyra": str(designs),
        "gsdesign": "4 distinct values",
        "deviation": None,
        "pass": distinct,
    })

    # Auto futility inherits, so moving efficacy gamma moves BOTH rules. This
    # is the magnitude quoted in the UI warning; if it stops holding, the
    # warning is misleading.
    rows.append({
        "test": "[discrimination] auto-inherit: gamma -4 -> +1 moves max N 483 -> 636",
        "zetyra": f"{designs[-4.0]} -> {designs[1.0]}",
        "gsdesign": "483 -> 636",
        "deviation": None,
        "pass": designs[-4.0] == 483 and designs[1.0] == 636,
    })

    # Explicit futility gamma must override inheritance rather than read as
    # absent. 0 is the dangerous value: it is falsy, so a truthiness test
    # anywhere in the chain silently restores the inherited gamma.
    inherited = client.gsd(**base, efficacy_hsd_gamma=1.0)
    overridden = client.gsd(**base, efficacy_hsd_gamma=1.0,
                            futility_hsd_gamma=0.0)
    rows.append({
        "test": "[discrimination] explicit futility gamma=0 overrides inheritance",
        "zetyra": f"auto={inherited['n_max']} explicit0={overridden['n_max']}",
        "gsdesign": "different",
        "deviation": None,
        "pass": inherited["n_max"] != overridden["n_max"]
                and (overridden.get("resolved_spending") or {}).get(
                    "futility_hsd_gamma") == 0.0,
    })

    # Omitting gamma must reproduce the historical fixed -4 exactly, or every
    # design saved before this feature silently changed meaning.
    omitted = client.gsd(**base)
    rows.append({
        "test": "[back-compat] omitted gamma == explicit -4",
        "zetyra": omitted["n_max"],
        "gsdesign": designs[-4.0],
        "deviation": None,
        "pass": omitted["n_max"] == designs[-4.0]
                and omitted["efficacy_boundaries"] ==
                    client.gsd(**base, efficacy_hsd_gamma=-4.0)["efficacy_boundaries"],
    })

    # A gamma that did not shape the design must not be reported as if it had.
    pocock = client.gsd(k=3, alpha=0.025, power=0.90, effect_size=0.3,
                        spending_function="Pocock",
                        beta_spending_function="none",
                        efficacy_hsd_gamma=1.0)
    res = pocock.get("resolved_spending") or {}
    rows.append({
        "test": "[contract] inactive gamma reported as null under Pocock",
        "zetyra": str(res.get("efficacy_hsd_gamma")),
        "gsdesign": "None",
        "deviation": None,
        "pass": res.get("efficacy_function") == "Pocock"
                and res.get("efficacy_hsd_gamma") is None,
    })
    return rows


def main():
    base_url = sys.argv[1] if len(sys.argv) > 1 else None
    client = get_client(base_url) if base_url else get_client()

    with open(FIXTURES) as fh:
        cases = json.load(fh)

    # MANIFEST. Partitioned once, up front, so the run is measured against a
    # declared expectation rather than against whatever it happened to do.
    numerical = [c for c in cases if c["inputs"]["k"] <= CERTIFIED_MAX_K]
    rejections = [c for c in cases if c["inputs"]["k"] > CERTIFIED_MAX_K]
    gate = Gate(
        suite="GSD HSD gamma",
        suite_id="gsd-hsd-gamma",
        expected_numerical={c["test_name"] for c in numerical}
        | {"discrimination-and-contract"},
        expected_rejection={c["test_name"] for c in rejections},
    )

    ids = [c["test_name"] for c in cases]
    if len(ids) != len(set(ids)):
        dupes = sorted({i for i in ids if ids.count(i) > 1})
        print(f"FIXTURE HAS DUPLICATE CASE IDS: {dupes}")
        sys.exit(1)

    versions = {c.get("gsdesign_version") for c in cases}
    print("=" * 78)
    print(f"GSD HWANG-SHIH-DECANI GAMMA VALIDATION vs gsDesign "
          f"{'/'.join(sorted(v for v in versions if v))}")
    print(f"{len(numerical)} numerical designs + {len(rejections)} "
          f"expected rejections (ceiling k<={CERTIFIED_MAX_K})")
    print("=" * 78)

    results = []
    for case in numerical:
        rows = _rows_for_case(client, case)
        results.extend(rows)
        gate.record_numerical(
            case["test_name"], all(r["pass"] for r in rows),
            detail="; ".join(r["test"] for r in rows if not r["pass"])[:200],
        )
    for case in rejections:
        results.extend(_rejection_rows_for_case(client, case, gate))

    disc = _rows_for_discrimination(client)
    results.extend(disc)
    gate.record_numerical(
        "discrimination-and-contract", all(r["pass"] for r in disc),
        detail="; ".join(r["test"] for r in disc if not r["pass"])[:200],
    )

    df = pd.DataFrame(results)
    pd.set_option("display.max_rows", None)
    pd.set_option("display.width", 200)
    print(df.to_string(index=False))

    out_dir = os.path.join(HERE, "results")
    os.makedirs(out_dir, exist_ok=True)
    df.to_csv(os.path.join(out_dir, "gsd_hsd_gamma_validation.csv"), index=False)

    n_pass = int(df["pass"].sum())
    print(f"\n{n_pass}/{len(df)} assertions passed "
          f"({len(df) - sum(1 for r in results if 'EXPECTED REJECTION' in r['test'] or 'NOT PRODUCED' in r['test'])} numerical, "
          f"{sum(1 for r in results if 'EXPECTED REJECTION' in r['test'] or 'NOT PRODUCED' in r['test'])} rejection)")

    # Never returns: prints the structured summary and exits. A suite cannot
    # fall off the end silently.
    gate.finish()


if __name__ == "__main__":
    main()
